### ISSUE TITLE
fs-uae-launcher 2.8.3 on Linux: get_handler: TypeError NoneType object is not callable

### ISSUE THREAD

**Issue by rubin55** [FrodeSolheim/fs-uae#147]
Running fs-uae and fs-uae-launcher 2.8.3 on Gentoo Linux. With some (not all) WHDLoad games, I get the following:

```
ImplicitConfigHandler.do_update
split_path /home/rubin/FS-UAE/Hard Drives/Codename Iceman.lha#/CodeNameIceman/CodeNameIceman.slave
split_path /home/rubin/FS-UAE/Hard Drives/Codename Iceman.lha#/CodeNameIceman/CodeNameIceman.slave
get_handler /home/rubin/FS-UAE/Hard Drives/Codename Iceman.lha
TypeError("'NoneType' object is not callable",)
<Task "Amiga Launch Task"> failed "[Errno 2] No such file or directory: 'CodeNameIceman/CodeNameIceman.slave'"
Traceback (most recent call last):
  File "/usr/share/fs-uae-launcher/fsbc/task.py", line 59, in __run
    self.run()
  File "/usr/share/fs-uae-launcher/launcher/fs_uae_launcher.py", line 515, in run
    self.launch_handler.run_sequence()
  File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 117, in run_sequence
    self.prepare()
  File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 101, in prepare
    self.prepare_hard_drives()
  File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 373, in prepare_hard_drives
    self.prepare_hard_drive(i)
  File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 389, in prepare_hard_drive
    self.unpack_game_hard_drive(index, src)
  File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 534, in unpack_game_hard_drive
    self.fsgs.file.copy_game_file("sha1://{0}".format(sha1), dst_file)
  File "/usr/share/fs-uae-launcher/fsgs/FSGameSystemContext.py", line 167, in copy_game_file
    return self._copy_game_file(src, dst)
  File "/usr/share/fs-uae-launcher/fsgs/FSGameSystemContext.py", line 179, in _copy_game_file
    ifs = self.open(src, prefer_path=True)
  File "/usr/share/fs-uae-launcher/fsgs/FSGameSystemContext.py", line 94, in open
    uri = self.convert_uri(uri, prefer_path=prefer_path)
  File "/usr/share/fs-uae-launcher/fsgs/FSGameSystemContext.py", line 90, in convert_uri
    return Archive(uri).open(uri)
  File "/usr/share/fs-uae-launcher/fsgs/Archive.py", line 254, in open
    return self.get_handler().open(sub_path)
  File "/usr/share/fs-uae-launcher/fsgs/Archive.py", line 169, in open
    return open(path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'CodeNameIceman/CodeNameIceman.slave'

```

**Comment by rubin55** [comment]
I traced this back to actually not having lha support for Python installed; it happened only with lha compressed WHDload images! Closed!
