### ISSUE TITLE
FS-UAE crashes on exit in some circumstances

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#25]
from jbl007:
"crashes with a chance of 95% on exit if "window_width" and/or "window_height" is in the config.

It seems to crash at random positions. Here is one example (gdb):"

```
amiga_quit
UAE emulation core is quitting
[Thread 0xbfafab40 (LWP 8216) exited]
[Thread 0xc26fbb40 (LWP 8215) exited]
[Thread 0xf34e4b40 (LWP 8214) exited]

Program received signal SIGSEGV, Segmentation fault.
luaH_getstr (t=0xc3329b0, key=0xc333290) at libfsemu/src/lua/ltable.c:470
470     if (ttisshrstring(gkey(n)) && eqshrstr(rawtsvalue(gkey(n)), key))
(gdb) bt
#0  luaH_getstr (t=0xc3329b0, key=0xc333290) at libfsemu/src/lua/ltable.c:470
#1  0x08525993 in luaH_get (t=0xc3329b0, key=0xc333180) at libfsemu/src/lua/ltable.c:484
#2  0x085275a1 in luaV_gettable (L=0xc333608, t=0xc332b80, key=0xc333180, val=0xc333180) at libfsemu/src/lua/lvm.c:117
#3  0x08510332 in lua_getglobal (L=0xc333608, var=0x870ab87 "on_fs_emu_render_frame") at libfsemu/src/lua/lapi.c:605
#4  0x084d0031 in fs_emu_lua_run_handler (name=0x870ab87 "on_fs_emu_render_frame") at libfsemu/src/emu/emu_lua.c:20
#5  0x084d7050 in render_frame (alpha=1, perspective=313534184) at libfsemu/src/emu/render.c:915
#6  0x084d8c88 in fs_emu_video_render_function () at libfsemu/src/emu/render.c:1980
#7  0x0852baab in render_frame () at libfsemu/src/ml/render.c:222
#8  fs_ml_render_iteration () at libfsemu/src/ml/render.c:648
#9  0x0852cfb3 in fs_ml_main_loop () at libfsemu/src/ml/sdl.c:992
#10 0x084cfcb1 in fs_emu_run (function=0x8601ef0 <main_function>) at libfsemu/src/emu/emu.c:455
#11 0x08050360 in main (argc=3, argv=0xffffd564) at src/fs-uae/main.c:1155
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
luaH_getstr (t=0xc3329b0, key=0xc333290) at libfsemu/src/lua/ltable.c:470
470     if (ttisshrstring(gkey(n)) && eqshrstr(rawtsvalue(gkey(n)), key))
(gdb) c
Continuing.
[Thread 0xbebf9b40 (LWP 8237) exited]
[Thread 0xf68aeb40 (LWP 8212) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) q
```

**Comment by FrodeSolheim** [comment]
Seems to be related to LUA. LUA scripting is currently disabled, and I'm not sure that it will be re-enabled again.
