### ISSUE TITLE
Launcher doesn't start (flatpak)

### ISSUE THREAD

**Issue by pezz** [FrodeSolheim/fs-uae#355]
Seeing this when trying to start the flatpak launcher:

```
% flatpak run --command=fs-uae-launcher net.fsuae.FS-UAE
<bunch of python output>
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

Not sure if any other info is needed?

Edit: forgot the version, latest stable 3.1.66 built 4 days ago or so.

**Comment by mattx1986** [comment]
I have the same issue on Linux Mint Mate. FS-UAE works as normal, but FS-UAE Launcher stopped working after I did flatpak updates. In the terminal it spits the same error message as @pezz wrote above.

**Comment by jkoeble** [comment]
I have similar issues on Ubuntu 24.10, see attached log file. Happened after the most recent flatpak update.
[fs-uae-launcher.log.txt](https://github.com/user-attachments/files/17904841/fs-uae-launcher.log.txt)

**Comment by jkoeble** [comment]
Downgrading tp the previous flatpak release solves the issue, like e.g.:
sudo flatpak update --commit=6f238c385fd1e3ee70025058d4f92ebef71f3060cf10f70aeb52917e8398a3b3 net.fsuae.FS-UAE

**Comment by mattx1986** [comment]
@pezz Thanks for the solution. Even if it's not perfect FS-UAE Launcher works again. Thanks to you I've learned that how to downgrade Flatpaks to make some other apps work again if needed. :smiley: 
![Zrzut ekranu z 2024-11-27 19-07-58](https://github.com/user-attachments/assets/dec4f0a9-301f-4971-b178-33cc122d14cd)

**Comment by terzag** [comment]
Using Xubuntu 24.04.

I noticed yesterday that the launcher wouldn't run (not sure since when, haven't used it in a while). I have a bit more Python errors when trying to start it from a terminal, FWIW:

```
Unhandled exception detected in thread MainThread:
  ModuleNotFoundError:exceptions.py:<module>:2

Traceback (most recent call last):
  File "/app/bin/fs-uae-launcher", line 121, in <module>
    main()
  File "/app/bin/fs-uae-launcher", line 118, in main
    launcher.apps.main()
  File "/app/share/fs-uae-launcher/launcher/apps/__init__.py", line 137, in main
    app_main()
  File "/app/share/fs-uae-launcher/launcher/apps/fs_uae_launcher.py", line 22, in app_main
    from launcher.launcherapp import LauncherApp
  File "/app/share/fs-uae-launcher/launcher/launcherapp.py", line 20, in <module>
    from fsgs.context import fsgs
  File "/app/share/fs-uae-launcher/fsgs/context.py", line 1, in <module>
    from .FSGameSystemContext import FSGameSystemContext
  File "/app/share/fs-uae-launcher/fsgs/FSGameSystemContext.py", line 16, in <module>
    from fsgs.download import Downloader, offline_mode
  File "/app/share/fs-uae-launcher/fsgs/download.py", line 6, in <module>
    import requests
  File "/app/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/app/lib/python3.12/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/app/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/app/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

**Comment by sairuk** [comment]
I thought i'd already commented on this but I see there is still some chatter on eab. if you want to work around this instead of downgrading

install a later `urllib3` (3.2.3 currently works) outside of any standard python paths and pass a `PYTHONPATH` env var to the flatpak to append this path to `sys.path`, the flatpak must be able to see the new path so if you need to add an additional filesystems override for this.

Doesn't matter how you do it, either `run`, edit the shortcut, create an overrides file, flatseal etc.

for example
```
$ mkdir -p $HOME/tmp/python
$ pip3 install --target $HOME/tmp/python urllib3 --upgrade
$ /usr/bin/flatpak run  --command=fs-uae-launcher --env=PYTHONPATH=$HOME/tmp/python net.fsuae.FS-UAE
```

**Comment by FrodeSolheim** [comment]
Hi, the FS-UAE flatpak is unofficial, and is not created nor maintained by me. This looks like a packaging or dependency issue in the flatpak and not an issue with FS-UAE (Launcher) as such.

**Comment by rofl0r** [comment]
hi @FrodeSolheim, glad to see you alive! (and hopefully well)
